getPagination('#table-id');function getPagination(table){var lastPage=1;$('#maxRows').on('change',function(evt){lastPage=1;$('.pagination').find("li").slice(1,-1).remove();var trnum=0;var maxRows=parseInt($(this).val());if(maxRows==5000){$('.pagination').hide()}else{$('.pagination').show()}
var totalRows=$(table+' tbody tr').length;$(table+' tr:gt(0)').each(function(){trnum++;if(trnum>maxRows){$(this).hide()}if(trnum<=maxRows){$(this).show()}});if(totalRows>maxRows){var pagenum=Math.ceil(totalRows/maxRows);for(var i=1;i<=pagenum;){$('.pagination #prev').before('<li data-page="'+i+'">\
            <span>'+i++ +'<span class="sr-only">(current)</span></span>\
          </li>').show()}}
$('.pagination [data-page="1"]').addClass('active');$('.pagination li').on('click',function(evt){evt.stopImmediatePropagation();evt.preventDefault();var pageNum=$(this).attr('data-page');var maxRows=parseInt($('#maxRows').val());if(pageNum=="prev"){if(lastPage==1){return}
pageNum=--lastPage}
if(pageNum=="next"){if(lastPage==($('.pagination li').length-2)){return}
pageNum=++lastPage}
lastPage=pageNum;var trIndex=0;$('.pagination li').removeClass('active');$('.pagination [data-page="'+lastPage+'"]').addClass('active');$(table+' tr:gt(0)').each(function(){trIndex++;if(trIndex>(maxRows*pageNum)||trIndex<=((maxRows*pageNum)-maxRows)){$(this).hide()}else{$(this).show()}})})}).val(5).change()}
$(function(){$('table tr:eq(0)').prepend('<th> ID </th>')
var id=0;$('table tr:gt(0)').each(function(){id++
$(this).prepend('<td>'+id+'</td>')})})
function byVIN(){document.getElementById("info-right__middle-second-item").style.border="1px solid #ccc";document.getElementById("info-right__middle-second-item").style.color="#ccc";document.getElementById("info-right__middle-second-item-content").style.pointerEvents="none";document.getElementById("btn2").style.background="#ccc";document.getElementById("info-right__middle-first-item").style.border="1px solid black";document.getElementById("info-right__middle-first-item").style.color="black";document.getElementById("info-right__middle-first-item-content").style.pointerEvents="visible";document.getElementById("btn1").style.background="#84c39c"};function byPlate(){document.getElementById("info-right__middle-first-item").style.border="1px solid #ccc";document.getElementById("info-right__middle-first-item").style.color="#ccc";document.getElementById("info-right__middle-first-item-content").style.pointerEvents="none";document.getElementById("btn1").style.background="#ccc";document.getElementById("info-right__middle-second-item").style.border="1px solid black";document.getElementById("info-right__middle-second-item").style.color="black";document.getElementById("info-right__middle-second-item-content").style.pointerEvents="visible";document.getElementById("btn2").style.background="#84c39c"}
